apiVersion: apps/v1
kind: Deployment
metadata:
  name: createyourprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: createyourprofile
  template:
    metadata:
      labels:
        app: createyourprofile
    spec:
      containers:
      - name: createyourprofile
        image: anmolverma404/createyourprofile
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: createyourprofile
spec:
  selector:
    app: createyourprofile
  ports:
  - port: 4002
    targetPort: 4002
