apiVersion: apps/v1
kind: Deployment
metadata:
  name: invcode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invcode
  template:
    metadata:
      labels:
        app: invcode
    spec:
      containers:
      - name: invcode
        image: anmolverma404/invcode
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: invcode
spec:
  selector:
    app: invcode
  ports:
  - port: 4001
    targetPort: 4001
